packages:
  - "apps/*"
  - "apps/ledger-live-desktop/tests/utils/**"
  - "libs/*"
  - "libs/ledgerjs/**"
  - "libs/ui/packages/*"
  - "libs/ledger-live-common/tools"
  - "tools/**"
  - "libs/ledger-common"
  - "libs/cosmos"
